/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: {
          900: "#0f172a",
          700: "#334155",
        },
        clay: {
          50: "#f9f5ef",
          100: "#f3ede3",
          200: "#e7dcc9",
        },
        sea: {
          600: "#1f7a8c",
          700: "#175c68",
        },
        sunset: {
          400: "#f59e0b",
          500: "#e07a1f",
        },
        // Stitch CulinShare colors
        primary: "#ab2e10",
        secondary: "#665e49",
        tertiary: "#575f41",
        background: "#fbf9f8",
        surface: "#fbf9f8",
        "surface-variant": "#e4e2e2",
        "surface-dim": "#dbd9d9",
        "surface-container": "#f0eded",
        "surface-container-low": "#f5f3f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e2",
        "surface-bright": "#fbf9f8",
        "on-background": "#1b1c1c",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#59413b",
        outline: "#8d716a",
        "outline-variant": "#e1bfb7",
        "primary-container": "#cd4727",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdad2",
        "primary-fixed-dim": "#ffb4a3",
        "on-primary-fixed": "#3d0700",
        "on-primary-fixed-variant": "#8b1b00",
        "secondary-container": "#ebdfc4",
        "on-secondary-container": "#6b624d",
        "secondary-fixed": "#eee1c7",
        "secondary-fixed-dim": "#d1c5ac",
        "on-secondary-fixed": "#211b0b",
        "on-secondary-fixed-variant": "#4e4633",
        "tertiary-container": "#6f7858",
        "on-tertiary-container": "#fbffe6",
        "tertiary-fixed": "#dee7c0",
        "tertiary-fixed-dim": "#c1cba6",
        "on-tertiary-fixed": "#171e06",
        "on-tertiary-fixed-variant": "#424a2e",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f2f0f0",
        "inverse-primary": "#ffb4a3",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#ae3113",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        md: "24px",
        lg: "48px",
        "max-width": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        xl: "80px",
        gutter: "24px",
        sm: "12px",
        base: "8px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui"],
        display: ["Playfair Display", "ui-serif", "Georgia", "serif"],
        "display-lg": ["Playfair Display"],
        "label-sm": ["Inter"],
        "display-lg-mobile": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Playfair Display"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      boxShadow: {
        float: "0 20px 50px -20px rgba(15, 23, 42, 0.35)",
        soft: "0 4px 20px rgba(72, 72, 72, 0.08)",
        recipe: "0px 4px 20px rgba(72, 72, 72, 0.08)",
        "recipe-hover": "0px 8px 30px rgba(72, 72, 72, 0.12)",
      },
    },
  },
  plugins: [],
};

