-- =================================================================
DROP DATABASE IF EXISTS CulinShare;

-- Tạo database mới
CREATE DATABASE CulinShare
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE CulinShare;

-- =================================================================
-- DROP TABLES (IN CORRECT ORDER FOR FOREIGN KEYS)
-- =================================================================
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS saved_recipes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS recipe_images;
DROP TABLE IF EXISTS recipe_steps;
DROP TABLE IF EXISTS recipe_ingredients;
DROP TABLE IF EXISTS recipe_categories;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS users;

-- =================================================================
-- CREATE TABLES
-- =================================================================

-- 1. Table: users
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    
    -- Thông tin đăng nhập
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    
    -- Thông tin cá nhân
    full_name VARCHAR(100) DEFAULT NULL,
    avatar_url VARCHAR(255) DEFAULT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    bio TEXT DEFAULT NULL,
    facebook_url VARCHAR(255) DEFAULT NULL,
    instagram_username VARCHAR(100) DEFAULT NULL,
    cuisine_preferences TEXT DEFAULT NULL,
    daily_budget DECIMAL(12,2) DEFAULT NULL,
    
    -- Phân quyền
    role VARCHAR(20) DEFAULT 'user',
    
    -- Chỉ số sức khỏe (phục vụ tính BMI & TDEE)
    height INT DEFAULT NULL,
    weight INT DEFAULT NULL,
    activity_level VARCHAR(20) DEFAULT 'sedentary', -- 'sedentary', 'moderate', 'active'
    
    -- Xác thực email
    is_verified TINYINT(1) DEFAULT 0,
    
    -- OTP
    otp_code VARCHAR(6) DEFAULT NULL,
    otp_expires_at DATETIME DEFAULT NULL,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_users_username (username),
    INDEX idx_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Table: recipes
CREATE TABLE recipes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    author_id INT NOT NULL,
    title VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL UNIQUE,
    description TEXT DEFAULT NULL,
    cover_image_url VARCHAR(255) DEFAULT NULL,
    video_url VARCHAR(255) DEFAULT NULL,
    prep_time_minutes INT DEFAULT 0,
    cook_time_minutes INT DEFAULT 0,
    servings INT DEFAULT 0,
    calories INT DEFAULT 0,
    difficulty ENUM('dễ', 'trung bình', 'khó') DEFAULT 'dễ',
    status ENUM('draft', 'pending', 'published') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_recipes_author_id (author_id),
    INDEX idx_recipes_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Table: categories
CREATE TABLE categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT DEFAULT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_categories_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Table: recipe_categories
CREATE TABLE recipe_categories (
    recipe_id INT NOT NULL,
    category_id INT NOT NULL,
    PRIMARY KEY (recipe_id, category_id),
    CONSTRAINT uq_recipe_category UNIQUE (recipe_id, category_id),

    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    INDEX idx_recipe_categories_recipe_id (recipe_id),
    INDEX idx_recipe_categories_category_id (category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Table: recipe_ingredients
CREATE TABLE recipe_ingredients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    recipe_id INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    quantity VARCHAR(50) DEFAULT NULL,
    unit VARCHAR(50) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    INDEX idx_recipe_ingredients_recipe_id (recipe_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Table: recipe_steps
CREATE TABLE recipe_steps (
    id INT AUTO_INCREMENT PRIMARY KEY,
    recipe_id INT NOT NULL,
    step_number INT NOT NULL,
    instruction TEXT NOT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    timer_seconds INT DEFAULT 0,

    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    INDEX idx_recipe_steps_recipe_id (recipe_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. Table: recipe_images
CREATE TABLE recipe_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    recipe_id INT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    INDEX idx_recipe_images_recipe_id (recipe_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. Table: reviews
CREATE TABLE reviews (
    id INT AUTO_INCREMENT PRIMARY KEY,
    recipe_id INT NOT NULL,
    user_id INT NOT NULL,
    rating INT NOT NULL,
    comment TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uq_reviews_user_recipe UNIQUE (user_id, recipe_id),
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_reviews_recipe_id (recipe_id),
    INDEX idx_reviews_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. Table: comments
CREATE TABLE comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    recipe_id INT NOT NULL,
    user_id INT NOT NULL,
    parent_id INT DEFAULT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE CASCADE,
    INDEX idx_comments_recipe_id (recipe_id),
    INDEX idx_comments_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. Table: saved_recipes
CREATE TABLE saved_recipes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    recipe_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_saved_recipes_user_recipe UNIQUE (user_id, recipe_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    INDEX idx_saved_recipes_user_id (user_id),
    INDEX idx_saved_recipes_recipe_id (recipe_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. Table: follows
CREATE TABLE follows (
    id INT AUTO_INCREMENT PRIMARY KEY,
    follower_id INT NOT NULL,
    following_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_follows_follower_following UNIQUE (follower_id, following_id),
    CONSTRAINT chk_follows_prevent_self_follow CHECK (follower_id <> following_id),
    FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_follows_follower_id (follower_id),
    INDEX idx_follows_following_id (following_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. Table: notifications
CREATE TABLE notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    sender_id INT NOT NULL,
    type ENUM('comment', 'review', 'follow') NOT NULL,
    recipe_id INT DEFAULT NULL,
    message TEXT NOT NULL,
    is_read TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE SET NULL,
    INDEX idx_notifications_user_id (user_id),
    INDEX idx_notifications_is_read (user_id, is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =================================================================
-- SEED DATA
-- =================================================================

-- 1. Seed users
INSERT INTO users (id, username, password_hash, email, full_name, avatar_url, phone, address, bio, facebook_url, instagram_username, cuisine_preferences, daily_budget, role, height, weight, activity_level, is_verified)
VALUES
(1, 'admin', '$2a$10$0FGPq/9.5sY6AiO3SkFLFuvguPCR1kFyZld/kWxkwzhSv3010KFru', 'admin@culinshare.com', 'Hệ thống Admin', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb', NULL, NULL, 'Tài khoản quản trị viên tối cao của hệ thống.', NULL, NULL, NULL, NULL, 'admin', NULL, NULL, 'sedentary', 1),
(2, 'hoanganh', '$2a$10$0FGPq/9.5sY6AiO3SkFLFuvguPCR1kFyZld/kWxkwzhSv3010KFru', 'chef.hoanganh@culinshare.com', 'Chef Hoàng Anh', 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c', NULL, NULL, 'Đầu bếp chuyên nghiệp với hơn 10 năm kinh nghiệm trong ẩm thực truyền thống Việt Nam. Đam mê gìn giữ hương vị cội nguồn.', NULL, NULL, NULL, NULL, 'user', NULL, NULL, 'sedentary', 1),
(3, 'nguyenvana', '$2a$10$0FGPq/9.5sY6AiO3SkFLFuvguPCR1kFyZld/kWxkwzhSv3010KFru', 'nguyenvana@gmail.com', 'Nguyễn Văn A', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815952/mamngon/avatars/avatar-1782815952905.jpg', NULL, NULL, 'Yêu thích nấu ăn và khám phá ẩm thực vùng miền.', NULL, NULL, NULL, NULL, 'user', NULL, NULL, 'sedentary', 1),
(4, 'tranthib', '$2a$10$0FGPq/9.5sY6AiO3SkFLFuvguPCR1kFyZld/kWxkwzhSv3010KFru', 'tranthib@gmail.com', 'Trần Thị B', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330', NULL, NULL, 'Người nội trợ gia đình luôn tìm kiếm công thức lành mạnh cho con cái.', NULL, NULL, NULL, NULL, 'user', NULL, NULL, 'sedentary', 1),
(5, 'levanc', '$2a$10$0FGPq/9.5sY6AiO3SkFLFuvguPCR1kFyZld/kWxkwzhSv3010KFru', 'levanc@gmail.com', 'Lê Văn C', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e', NULL, NULL, 'Học sinh sinh viên tập tành nấu ăn, thích các món chay và nhanh gọn.', NULL, NULL, NULL, NULL, 'user', NULL, NULL, 'sedentary', 1),
(6, 'cheflan', '$2a$10$0FGPq/9.5sY6AiO3SkFLFuvguPCR1kFyZld/kWxkwzhSv3010KFru', 'chef.lan@culinshare.com', 'Chef Minh Lan', 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f', NULL, NULL, 'Chuyên món Việt gia đình và các món vùng miền.', NULL, NULL, NULL, NULL, 'user', NULL, NULL, 'sedentary', 1),
(7, 'chefquang', '$2a$10$0FGPq/9.5sY6AiO3SkFLFuvguPCR1kFyZld/kWxkwzhSv3010KFru', 'chef.quang@culinshare.com', 'Chef Quốc Quang', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6', NULL, NULL, 'Yêu thích hải sản, món nướng và bếp hiện đại.', NULL, NULL, NULL, NULL, 'user', NULL, NULL, 'sedentary', 1);

-- 2. Seed categories
INSERT INTO categories (id, name, slug, description, image_url)
VALUES
(1, 'Món Việt', 'mon-viet', 'Những món ăn truyền thống đậm đà bản sắc Việt Nam.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782816021/mamngon/categories/mdxkad3vokex15suyafh.jpg'),
(2, 'Món chay', 'mon-chay', 'Các món ăn chay thanh tịnh, tốt cho sức khỏe và vóc dáng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815959/mamngon/categories/x0i3tpcox94wfrmafxvw.jpg'),
(3, 'Món tráng miệng', 'mon-trang-mieng', 'Chè, bánh ngọt, hoa quả dầm và các món giải nhiệt ngọt ngào.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782816015/mamngon/categories/oejvp9ql8q2av1pipeq7.jpg'),
(4, 'Món ăn sáng', 'mon-an-sang', 'Các món ăn nhiều dưỡng chất khởi đầu ngày mới tràn đầy năng lượng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815953/mamngon/categories/eennuvmljv5hdwttjsnd.jpg'),
(5, 'Món nước', 'mon-nuoc', 'Phở, bún, mì và các món có nước dùng nóng hổi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782816009/mamngon/categories/wg6qomcwrbdwlhg1qgcb.jpg'),
(6, 'Hải sản', 'hai-san', 'Công thức từ tôm, cua, cá, mực tươi rói.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815946/mamngon/categories/fq170l2r5mbuvmxoiyws.jpg'),
(7, 'Món lành mạnh', 'mon-lanh-manh', 'Công thức ít dầu mỡ, nhiều rau xanh tốt cho dáng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815965/mamngon/categories/rgfbgzmla9bqr8hfe9no.jpg');

-- 3. Seed recipes
INSERT INTO recipes (id, author_id, title, slug, description, cover_image_url, video_url, prep_time_minutes, cook_time_minutes, servings, calories, difficulty, status)
VALUES
(1, 2, 'Phở bò Hà Nội', 'pho-bo-ha-noi', 'Phở bò Hà Nội truyền thống thơm ngon đậm đà, nước dùng ngọt thanh ninh từ xương bò và hương thảo mộc nướng quyến rũ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811000/mamngon/recipes/rngmtck4ym74nc2hhpvu.jpg', NULL, 45, 360, 4, 480, 'khó', 'published'),
(2, 2, 'Bún chả Hà Nội', 'bun-cha-ha-noi', 'Sự kết hợp hoàn hảo giữa chả viên nướng và chả miếng vàng sậm, ăn cùng nước chấm chua ngọt đu đủ xanh giòn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811005/mamngon/recipes/vg8gkkjkfddvjtttnl73.jpg', NULL, 30, 30, 4, 550, 'trung bình', 'published'),
(3, 6, 'Phở gà ta', 'pho-ga-ta', 'Món phở gà da vàng giòn ngọt thịt, nước phở thơm nhẹ hương hạt mùi nướng và lá chanh thái chỉ mỏng tanh.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811010/mamngon/recipes/sp4uyxajzxz1wpzugjq5.jpg', NULL, 25, 90, 4, 420, 'trung bình', 'published'),
(4, 6, 'Bún bò Huế', 'bun-bo-hue', 'Hương vị cay nồng chuẩn xứ Huế đậm đà mắm ruốc, thơm nức hương sả kết hợp giò heo béo ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815628/mamngon/recipes/auj7qhbjpovmdr7qtznp.jpg', NULL, 40, 180, 5, 560, 'khó', 'published'),
(5, 2, 'Mì Quảng gà nén', 'mi-quang-ga-nen', 'Sợi mì vàng dai kết hợp nhân thịt gà rim nghệ thơm lừng củ nén đập dập, bánh tráng giòn rụm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811062/mamngon/recipes/aoedlbbprhses7lury6r.jpg', NULL, 30, 45, 4, 510, 'trung bình', 'published'),
(6, 7, 'Hủ tiếu Nam Vang', 'hu-tieu-nam-vang', 'Món ăn giao thoa ẩm thực miền Nam đặc sắc với tôm sú tươi, trứng cút lòng đào và nước dùng ngọt từ xương ống.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811068/mamngon/recipes/lh9pcsqivwhkuyrm3wvc.jpg', NULL, 30, 90, 4, 490, 'trung bình', 'published'),
(7, 6, 'Cơm tấm sườn bì chả', 'com-tam-suon-bi-cha', 'Đĩa cơm tấm dẻo hạt ăn kèm sườn cốt lết nướng thơm ngậy, bì trộn thính và chả trứng hấp mềm mại.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811077/mamngon/recipes/h4izimooktlcjbpngadu.jpg', NULL, 35, 40, 4, 690, 'trung bình', 'published'),
(8, 6, 'Cơm gà Hội An', 'com-ga-hoi-an', 'Hạt cơm vàng óng dẻo bùi nấu bằng nước luộc gà và mỡ gà, ăn cùng gà xé phay bóp rau răm chua dịu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811088/mamngon/recipes/tjyxed2dfmy0nw9upc0m.jpg', NULL, 25, 45, 4, 540, 'trung bình', 'published'),
(9, 7, 'Cá lóc kho tộ miền Tây', 'ca-loc-kho-to-mien-tay', 'Khúc cá lóc đồng kho sền sệt trong tộ đất, thấm đẫm nước màu thốt nốt mặn ngọt đậm đà vị đưa cơm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811101/mamngon/recipes/jsz7xudg7bfegaikirsg.jpg', NULL, 20, 40, 4, 360, 'trung bình', 'published'),
(10, 2, 'Canh chua cá lóc miền Tây', 'canh-chua-ca-loc-mien-tay', 'Bát canh chua hài hòa vị chua thanh từ me, vị ngọt tự nhiên của cá và các loại rau bạc hà, đậu bắp giòn ngọt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815755/mamngon/recipes/hgs084skvaeullrl5m2c.jpg', NULL, 20, 20, 4, 240, 'dễ', 'published'),
(11, 6, 'Bún riêu cua bắp bò', 'bun-rieu-cua-bap-bo', 'Nước lèo thanh dịu ngọt cua đồng, riêu cua từng tảng xốp mềm ăn kèm bắp bò chần tươi roi rói.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811147/mamngon/recipes/eqvg8crd8vzfygtzbwhu.jpg', NULL, 35, 60, 4, 460, 'khó', 'published'),
(12, 2, 'Bún riêu ốc chuối đậu', 'bun-rieu-oc-chuoi-dau', 'Sự hòa quyện thú vị giữa ốc nhồi giòn sần sật, thịt ba chỉ thơm béo và nước canh chuối đậu đậm đà.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811151/mamngon/recipes/qlrvwz7lhbctmp0aexj6.jpg', NULL, 40, 50, 4, 450, 'khó', 'published'),
(13, 6, 'Bánh canh cua bể', 'banh-canh-cua-be', 'Sợi bánh canh bột lọc dai dẻo chan nước súp gạch cua sánh đỏ, đậm đà thịt cua bể ngọt lịm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811189/mamngon/recipes/aj1llcynmqb23wwhmqrd.jpg', NULL, 35, 50, 4, 490, 'trung bình', 'published'),
(14, 7, 'Lẩu Thái hải sản chua cay', 'lau-thai-hai-san-chua-cay', 'Bữa tiệc lẩu ấm cúng đậm đà hương vị sả chanh Thái Lan kết hợp tôm sú mực tươi rói chấm muối ớt xanh.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811193/mamngon/recipes/tm2llph1iwmdwphi7n7a.jpg', NULL, 35, 35, 6, 460, 'trung bình', 'published'),
(15, 6, 'Đậu hũ sốt cà chua chay', 'dau-hu-sot-ca-chua-chay', 'Món ăn gia đình chay tịnh giản dị, miếng đậu hũ chiên mềm thấm đẫm sốt cà chua ngọt đậm đà.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811197/mamngon/recipes/gfyf85yh3hzp9lwbfxcw.jpg', NULL, 10, 15, 3, 230, 'dễ', 'published'),
(16, 2, 'Gỏi cuốn tôm thịt heo', 'goi-cuon-tom-thit-heo', 'Cuốn bánh tráng mướt mát nhiều rau xanh ăn kèm thịt ba chỉ luộc và tôm sú luộc đỏ hồng chấm tương đậu phộng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811201/mamngon/recipes/vsabh7azbrh1o2cl83f1.jpg', NULL, 25, 15, 4, 250, 'dễ', 'published'),
(17, 7, 'Bò lúc lắc khoai tây chiên', 'bo-luc-lac-khoai-tay-chien', 'Những khối thịt bò thăn mềm mọng ngọt tự nhiên xào nhanh tay trên lửa lớn cùng hành tây ớt chuông đậm vị sốt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811205/mamngon/recipes/vk3tbp61nwaupuvk6l4d.jpg', NULL, 20, 15, 3, 430, 'trung bình', 'published'),
(18, 6, 'Nấm đùi gà kho tiêu xanh', 'nam-dui-ga-kho-tieu-xanh', 'Nấm đùi gà dai ngọt tự nhiên kho keo sền sệt với những chùm tiêu xanh nồng ấm vô cùng bắt cơm mâm chay.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811239/mamngon/recipes/gpoaiw2fchgolyqor549.jpg', NULL, 15, 20, 3, 180, 'dễ', 'published'),
(19, 2, 'Thịt ba chỉ kho tàu trứng cút', 'thit-ba-chi-kho-tau-trung-cut', 'Thịt ba chỉ mềm rục béo bùi đẫm nước dừa tươi kho cùng trứng cút nhỏ dai đậm đà truyền thống ngày Tết.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811280/mamngon/recipes/hg7shksa53w8uubkfoxl.jpg', NULL, 20, 75, 4, 580, 'trung bình', 'published'),
(20, 6, 'Gà kho gừng sợi ấm áp', 'ga-kho-gung-soi-am-ap', 'Thịt đùi gà săn chắc kho thơm cay cay ấm lòng sợi gừng non vàng ruộm, nước kho chan cơm cực ngon.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811285/mamngon/recipes/zqytffei8bbtahukdfnx.jpg', NULL, 15, 30, 4, 370, 'dễ', 'published'),
(21, 7, 'Mực ống xào sa tế cay cay', 'muc-ong-xao-sa-te-cay-cay', 'Mực ống tươi xào chín giòn sần sật bọc đều nước sốt sa tế cay nồng nàn ớt tỏi cực đưa cơm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811326/mamngon/recipes/frsbnykisij42slsf7i4.jpg', NULL, 15, 10, 3, 280, 'dễ', 'published'),
(22, 6, 'Cháo sườn heo non Hà Nội', 'chao-suon-heo-non-ha-noi', 'Bát cháo sườn xay sánh mịn ngọt thơm từ xương hầm, miếng sườn sụn non giòn ăn kèm quẩy nướng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811331/mamngon/recipes/llvuunvho3l0yt3fdah4.jpg', NULL, 20, 70, 4, 330, 'trung bình', 'published'),
(23, 2, 'Bánh xèo Nam Bộ giòn rụm', 'banh-xeo-nam-bo-gion-rum', 'Vỏ bánh xèo mỏng tang vàng ươm nghệ cốt dừa ôm nhân tôm đất thịt ba chỉ luộc cuốn cải xanh.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811337/mamngon/recipes/uv6ufaddy24ojfvuxhxa.jpg', NULL, 30, 25, 4, 450, 'trung bình', 'published'),
(24, 7, 'Cơm chiên hải sản dừa xiêm', 'com-chien-hai-san-dua-xiem', 'Hạt cơm chiên tơi vàng ruộm óng ánh tôm mực đậu hà lan bắp ngọt bày trong quả dừa xiêm mát mắt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811344/mamngon/recipes/ohomx9omkkugkfyj3z3x.jpg', NULL, 15, 15, 3, 520, 'dễ', 'published'),
(25, 2, 'Mì Ý sốt bò bằm Spaghetti', 'mi-y-sot-bo-bam-spaghetti', 'Sợi mì Ý luộc vừa chín tới ngập tràn trong nước sốt cà chua thịt bò bằm bổ dưỡng rắc phô mai Parmesan bùi béo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811354/mamngon/recipes/txpqcljwwht5lq0anur4.jpg', NULL, 15, 30, 3, 560, 'trung bình', 'published'),
(26, 6, 'Gỏi cuốn chay ngũ sắc', 'goi-cuon-chay-ngu-sac', 'Cuốn gỏi chay nhẹ nhàng tốt dáng ôm trọn bún, đậu hũ chiên, cà rốt dưa leo xà lách chấm tương bơ đậu phộng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811373/mamngon/recipes/apw2zg5500a7ohykyyhb.jpg', NULL, 20, 10, 3, 170, 'dễ', 'published'),
(27, 2, 'Chè khúc bạch nhãn tươi', 'che-khuc-bach-nhan-tuoi', 'Những viên khúc bạch sữa hạnh nhân béo ngậy mềm mịn trong nước đường phèn lá dứa nhãn cùi dày thơm mát.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811379/mamngon/recipes/ymba1rwgv2kkspxcbo7a.jpg', NULL, 25, 20, 5, 260, 'trung bình', 'published'),
(28, 7, 'Trà đào cam sả đá lạnh', 'tra-dao-cam-sa-da-lanh', 'Thức uống giải khát ngày hè sảng khoái thơm nồng nàn sả tươi vị chua thanh cam vàng đào miếng giòn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811383/mamngon/recipes/wm9fmltuyxikjau4icl0.jpg', NULL, 10, 10, 2, 120, 'dễ', 'published'),
(29, 2, 'Cà ri gà nước cốt dừa', 'ca-ri-ga-nuoc-cot-dua', 'Công thức làm Cà ri gà nước cốt dừa chuẩn vị thơm dẻo, giàu dinh dưỡng, rất thích hợp đãi cả nhà dịp cuối tuần.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811388/mamngon/recipes/berpccavobtxyc0zya86.jpg', NULL, 20, 30, 4, 510, 'trung bình', 'published'),
(30, 2, 'Bánh xèo miền Tây', 'banh-xeo-mien-tay', 'Công thức làm Bánh xèo miền Tây chuẩn vị thơm dẻo, giàu dinh dưỡng, rất thích hợp đãi cả nhà dịp cuối tuần.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811414/mamngon/recipes/icjlhh4o74g0q680sbui.jpg', NULL, 20, 30, 4, 450, 'trung bình', 'published'),
(31, 2, 'Sushi cuộn cá hồi Na Uy', 'sushi-cuon-ca-hoi-na-uy', 'Công thức làm Sushi cuộn cá hồi Na Uy chuẩn vị thơm dẻo, giàu dinh dưỡng, rất thích hợp đãi cả nhà dịp cuối tuần.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811418/mamngon/recipes/ncyyvlcmfe17tx09s065.jpg', NULL, 20, 30, 4, 390, 'khó', 'published'),
(32, 2, 'Tokbokki bánh gạo phô mai', 'tokbokki-banh-gao-pho-mai', 'Công thức làm Tokbokki bánh gạo phô mai chuẩn vị thơm dẻo, giàu dinh dưỡng, rất thích hợp đãi cả nhà dịp cuối tuần.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811428/mamngon/recipes/awicsqowgwqucgc1qi8d.jpg', NULL, 20, 30, 4, 420, 'dễ', 'published'),
(33, 2, 'Chè đậu xanh cốt dừa', 'che-dau-xanh-cot-dua', 'Công thức làm Chè đậu xanh cốt dừa chuẩn vị thơm dẻo, giàu dinh dưỡng, rất thích hợp đãi cả nhà dịp cuối tuần.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811432/mamngon/recipes/uh9cw0q5qn6ofumqlfzp.jpg', NULL, 20, 30, 4, 300, 'dễ', 'published'),
(34, 2, 'Xôi xoài cốt dừa Thái', 'xoi-xoai-cot-dua-thai', 'Công thức làm Xôi xoài cốt dừa Thái chuẩn vị thơm dẻo, giàu dinh dưỡng, rất thích hợp đãi cả nhà dịp cuối tuần.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811472/mamngon/recipes/fme7wgrzznuys8i2kflg.jpg', NULL, 20, 30, 4, 340, 'dễ', 'published'),
(35, 2, 'Sữa chua nếp cẩm dẻo bùi', 'sua-chua-nep-cam-deo-bui', 'Công thức làm Sữa chua nếp cẩm dẻo bùi chuẩn vị thơm dẻo, giàu dinh dưỡng, rất thích hợp đãi cả nhà dịp cuối tuần.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811476/mamngon/recipes/l4fuecn96mxxsxxteygo.jpg', NULL, 20, 30, 4, 220, 'dễ', 'published'),
(36, 2, 'Cà phê phin sữa đá Việt Nam', 'ca-phe-phin-sua-da-viet-nam', 'Công thức làm Cà phê phin sữa đá Việt Nam chuẩn vị thơm dẻo, giàu dinh dưỡng, rất thích hợp đãi cả nhà dịp cuối tuần.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811480/mamngon/recipes/kxs95xovt16siqyioe22.jpg', NULL, 20, 30, 4, 150, 'dễ', 'published');

-- 4. Seed recipe_ingredients
INSERT INTO recipe_ingredients (recipe_id, name, quantity, unit)
VALUES
(1, 'Xương ống bò', '2', 'kg'),
(1, 'Thịt ba chỉ nạm bò', '500', 'g'),
(1, 'Thịt thăn bò tái', '300', 'g'),
(1, 'Bánh phở tươi', '1', 'kg'),
(1, 'Hành tây', '2', 'củ'),
(1, 'Gừng già', '150', 'g'),
(1, 'Hành tím', '5', 'củ'),
(1, 'Thảo mộc nướng (quế, hồi, thảo quả, tiểu hồi)', '1', 'gói'),
(1, 'Nước mắm ngon', '100', 'ml'),
(1, 'Đường phèn', '30', 'g'),
(1, 'Hành lá, rau mùi', '1', 'đĩa'),
(2, 'Thịt ba chỉ', '500', 'g'),
(2, 'Thịt nạc vai xay', '500', 'g'),
(2, 'Đu đủ xanh, cà rốt', '1', 'bộ'),
(2, 'Bún tươi', '1', 'kg'),
(2, 'Hành tím, tỏi, ớt', '50', 'g'),
(2, 'Mật ong', '2', 'thìa canh'),
(2, 'Nước mắm ngon', '100', 'ml'),
(2, 'Dấm gạo', '50', 'ml'),
(2, 'Rau sống (xà lách, tía tô, húng)', '1', 'rổ'),
(3, 'Gà ta nguyên con', '1.5', 'kg'),
(3, 'Bánh phở', '800', 'g'),
(3, 'Hành tây, hành tím', '2', 'củ'),
(3, 'Gừng già', '100', 'g'),
(3, 'Hạt mùi, rễ mùi', '1', 'nhúm'),
(3, 'Lá chanh tươi', '10', 'lá'),
(3, 'Hành lá, rau mùi', '1', 'đĩa'),
(3, 'Gia vị hạt nêm, muối', 'vừa đủ', ''),
(4, 'Xương ống bò', '1.5', 'kg'),
(4, 'Bắp bò', '500', 'g'),
(4, 'Chân giò heo', '500', 'g'),
(4, 'Mắm ruốc Huế', '3', 'thìa canh'),
(4, 'Sả tươi', '8', 'nhánh'),
(4, 'Dầu điều tạo màu', '2', 'thìa canh'),
(4, 'Bún sợi to', '1', 'kg'),
(4, 'Rau sống (bắp chuối, giá, kinh giới)', '1', 'rổ'),
(4, 'Hành tây, hành lá', '1', 'đĩa'),
(5, 'Thịt gà ta', '1', 'kg'),
(5, 'Sợi mì Quảng vàng', '800', 'g'),
(5, 'Củ nén (hành tăm)', '50', 'g'),
(5, 'Bột nghệ', '1', 'thìa cà phê'),
(5, 'Nước mắm ngon', '3', 'thìa canh'),
(5, 'Bánh tráng nướng', '2', 'cái'),
(5, 'Đậu phộng rang', '50', 'g'),
(5, 'Rau sống (bắp chuối, cải non)', '1', 'đĩa'),
(6, 'Hủ tiếu khô', '500', 'g'),
(6, 'Xương ống heo', '1', 'kg'),
(6, 'Tôm sú tươi', '200', 'g'),
(6, 'Thịt băm', '150', 'g'),
(6, 'Gan heo', '150', 'g'),
(6, 'Trứng cút', '8', 'quả'),
(6, 'Tỏi băm làm tỏi phi', '50', 'g'),
(6, 'Hẹ tươi, cần tây', '1', 'nhúm'),
(7, 'Gạo tấm thơm', '400', 'g'),
(7, 'Sườn cốt lết heo', '4', 'miếng'),
(7, 'Da heo thái sợi (bì)', '150', 'g'),
(7, 'Thính gạo rang', '30', 'g'),
(7, 'Trứng gà', '4', 'quả'),
(7, 'Thịt băm làm chả', '150', 'g'),
(7, 'Mộc nhĩ, bún tàu', '30', 'g'),
(7, 'Mỡ hành, nước mắm tỏi ớt', '1', 'chén'),
(8, 'Gà ta nửa con', '800', 'g'),
(8, 'Gạo tẻ thơm', '300', 'g'),
(8, 'Nghệ tươi đập dập', '1', 'củ'),
(8, 'Hành tây', '1', 'củ'),
(8, 'Rau răm', '1', 'mớ'),
(8, 'Nước cốt chanh', '2', 'thìa canh'),
(8, 'Hành phi', '30', 'g'),
(8, 'Gia vị hạt tiêu, muối', 'vừa đủ', ''),
(9, 'Cá lóc cắt khúc', '600', 'g'),
(9, 'Thịt ba chỉ heo', '150', 'g'),
(9, 'Nước màu đường thốt nốt', '2', 'thìa canh'),
(9, 'Nước mắm ngon', '4', 'thìa canh'),
(9, 'Hành tím, tỏi, ớt hiểm', '50', 'g'),
(9, 'Hành lá', '3', 'nhánh'),
(9, 'Nước dừa tươi', '200', 'ml'),
(9, 'Hạt tiêu đen xay', '1', 'thìa cà phê'),
(10, 'Cá lóc đồng', '500', 'g'),
(10, 'Bạc hà (dọc mùng)', '2', 'nhánh'),
(10, 'Đậu bắp, thơm (dứa)', '1', 'đĩa'),
(10, 'Cà chua, giá đỗ', '150', 'g'),
(10, 'Nước cốt me chua', '4', 'thìa canh'),
(10, 'Rau om, ngò gai', '1', 'nhúm'),
(10, 'Nước mắm, đường phèn', 'vừa đủ', ''),
(11, 'Cua đồng xay sẵn', '500', 'g'),
(11, 'Bắp bò hoa', '300', 'g'),
(11, 'Đậu hũ chiên', '2', 'bìa'),
(11, 'Cà chua', '3', 'quả'),
(11, 'Bún tươi', '800', 'g'),
(11, 'Mẻ chua hoặc dấm bỗng', '50', 'ml'),
(11, 'Mắm tôm ngon', '1', 'thìa canh'),
(11, 'Rau sống (hoa chuối, tía tô, kinh giới)', '1', 'rổ'),
(12, 'Ốc nhồi (ốc bươu)', '1', 'kg'),
(12, 'Thịt ba chỉ', '200', 'g'),
(12, 'Đậu phụ', '2', 'bìa'),
(12, 'Chuối xanh', '3', 'quả'),
(12, 'Lá lốt, tía tô', '1', 'nhúm'),
(12, 'Dấm bỗng rượu', '50', 'ml'),
(12, 'Bột nghệ', '1', 'thìa cà phê'),
(12, 'Mắm tôm', '1', 'thìa cà phê'),
(13, 'Sợi bánh canh bột lọc', '600', 'g'),
(13, 'Thịt cua bể gỡ sẵn', '200', 'g'),
(13, 'Xương ống heo làm nước dùng', '800', 'g'),
(13, 'Màu dầu điều', '2', 'thìa canh'),
(13, 'Bột năng tạo độ sánh', '20', 'g'),
(13, 'Hành phi', '20', 'g'),
(13, 'Ngò gai, hành lá', '1', 'nhúm'),
(13, 'Tiêu xay nhuyễn', '1', 'thìa cà phê'),
(14, 'Tôm sú tươi', '300', 'g'),
(14, 'Mực ống', '300', 'g'),
(14, 'Nghêu (ngao)', '500', 'g'),
(14, 'Sốt gia vị lẩu Thái Tom Yum', '1', 'gói'),
(14, 'Sả nhánh, củ riềng', '100', 'g'),
(14, 'Lá chanh Thái (Kaffir)', '10', 'lá'),
(14, 'Nấm kim châm, nấm đùi gà', '300', 'g'),
(14, 'Bún tươi hoặc mì gói', '800', 'g'),
(15, 'Đậu hũ trắng', '4', 'bìa'),
(15, 'Cà chua chín', '3', 'quả'),
(15, 'Hành boaro (kiệu)', '1', 'nhánh'),
(15, 'Hạt nêm chay từ nấm', '2', 'thìa cà phê'),
(15, 'Nước tương ngon', '1', 'thìa canh'),
(15, 'Hành lá cắt nhỏ', '2', 'nhánh'),
(15, 'Dầu ăn thực vật', '100', 'ml'),
(16, 'Bánh tráng cuốn dẻo', '1', 'gói'),
(16, 'Tôm sú tươi', '300', 'g'),
(16, 'Thịt ba chỉ heo', '300', 'g'),
(16, 'Bún tươi sợi nhỏ', '400', 'g'),
(16, 'Xà lách, rau thơm, hẹ', '200', 'g'),
(16, 'Tương hột (tương ngọt)', '100', 'ml'),
(16, 'Bơ đậu phộng', '2', 'thìa canh'),
(16, 'Đậu phộng giã nhỏ', '30', 'g'),
(17, 'Thăn bò mềm', '400', 'g'),
(17, 'Ớt chuông xanh, đỏ', '2', 'quả'),
(17, 'Hành tây', '1', 'củ'),
(17, 'Khoai tây tươi chiên', '200', 'g'),
(17, 'Hành tỏi băm nhuyễn', '30', 'g'),
(17, 'Hắc xì dầu, bơ lạt', '1.5', 'thìa canh'),
(17, 'Dầu hào ngon', '2', 'thìa canh'),
(17, 'Gia vị hạt tiêu', 'vừa đủ', ''),
(18, 'Nấm đùi gà nhỏ', '400', 'g'),
(18, 'Tiêu xanh cả chùm', '4', 'nhánh'),
(18, 'Nước tương đậu nành', '3', 'thìa canh'),
(18, 'Đường mía thốt nốt', '1.5', 'thìa canh'),
(18, 'Hành boaro băm nhỏ', '1', 'nhánh'),
(18, 'Ớt sừng chín đỏ', '1', 'quả'),
(18, 'Nước màu dừa chay', '1', 'thìa cà phê'),
(19, 'Thịt ba chỉ heo', '600', 'g'),
(19, 'Trứng cút luộc chín', '15', 'quả'),
(19, 'Nước dừa xiêm tươi', '400', 'ml'),
(19, 'Nước mắm cá cơm ngon', '4', 'thìa canh'),
(19, 'Hành tím, tỏi khô', '40', 'g'),
(19, 'Nước màu đường caramen', '1', 'thìa canh'),
(19, 'Ớt hiểm đỏ tươi', '2', 'quả'),
(20, 'Thịt đùi gà ta', '800', 'g'),
(20, 'Gừng non thái sợi', '50', 'g'),
(20, 'Hành tím củ băm nhuyễn', '20', 'g'),
(20, 'Nước mắm ngon', '3', 'thìa canh'),
(20, 'Đường màu dừa', '1', 'thìa canh'),
(20, 'Hành lá, ớt hiểm', '20', 'g'),
(20, 'Dầu ăn thực vật', '2', 'thìa canh'),
(21, 'Mực ống tươi', '500', 'g'),
(21, 'Sa tế tôm cay', '2', 'thìa canh'),
(21, 'Ớt chuông xanh, hành tây', '1', 'bộ'),
(21, 'Tỏi băm nhuyễn', '20', 'g'),
(21, 'Nước mắm ngon', '1', 'thìa canh'),
(21, 'Hành hoa xanh cọng', '30', 'g'),
(21, 'Hạt tiêu, dầu hào', 'vừa đủ', ''),
(22, 'Bột gạo tẻ lọc nước', '150', 'g'),
(22, 'Sườn sụn heo non', '400', 'g'),
(22, 'Xương ống heo lấy súp', '500', 'g'),
(22, 'Quẩy giòn ăn kèm', '5', 'cái'),
(22, 'Hành phi giòn thơm', '20', 'g'),
(22, 'Nước mắm, muối, tiêu', 'vừa đủ', ''),
(22, 'Ruốc thịt heo (chà bông)', '50', 'g'),
(23, 'Bột bánh xèo pha nghệ', '400', 'g'),
(23, 'Tôm đất nhỏ nguyên vỏ', '200', 'g'),
(23, 'Thịt ba chỉ heo thái mỏng', '200', 'g'),
(23, 'Nước cốt dừa béo', '200', 'ml'),
(23, 'Giá đỗ đỗ xanh sạch', '200', 'g'),
(23, 'Hành tây thái lát mỏng', '1', 'củ'),
(23, 'Rau cải xanh lớn, rau thơm', '1', 'rổ'),
(23, 'Nước mắm tỏi ớt chua ngọt', '1', 'bát'),
(24, 'Cơm nguội dẻo tơi', '3', 'bát'),
(24, 'Tôm sú tươi cắt hạt lựu', '100', 'g'),
(24, 'Mực tươi cắt hạt lựu', '100', 'g'),
(24, 'Lòng đỏ trứng gà', '2', 'quả'),
(24, 'Đậu Hà Lan, bắp ngọt', '100', 'g'),
(24, 'Trái dừa xiêm rỗng', '1', 'quả'),
(24, 'Tỏi băm hành phi', '30', 'g'),
(24, 'Hạt nêm nước tương tiêu', 'vừa đủ', ''),
(25, 'Mì Ý khô dạng sợi', '250', 'g'),
(25, 'Thịt vai bò băm nhuyễn', '250', 'g'),
(25, 'Cà chua chín xay mịn', '3', 'quả'),
(25, 'Hành tây thái hạt lựu', '1', 'củ'),
(25, 'Tỏi khô băm nhuyễn', '20', 'g'),
(25, 'Lá oregano khô thơm', '1', 'thìa cà phê'),
(25, 'Phô mai Parmesan bột', '20', 'g'),
(25, 'Bơ lạt hoặc dầu ô-liu', '2', 'thìa canh'),
(26, 'Bánh tráng cuốn dẻo', '1', 'gói'),
(26, 'Đậu hũ trắng chiên giòn', '2', 'bìa'),
(26, 'Cà rốt thái sợi chỉ', '1', 'củ'),
(26, 'Dưa leo thái thanh mỏng', '1', 'quả'),
(26, 'Bún tươi', '300', 'g'),
(26, 'Bơ sáp lát mỏng', '1', 'quả'),
(26, 'Bơ đậu phộng chay chấm', '3', 'thìa canh'),
(26, 'Rau xà lách húng lủi', '100', 'g'),
(27, 'Kem tươi Whipping Cream', '250', 'ml'),
(27, 'Sữa tươi không đường', '250', 'ml'),
(27, 'Bột Gelatin làm đông', '20', 'g'),
(27, 'Nhãn xuồng tươi tách hạt', '500', 'g'),
(27, 'Hạnh nhân lát rang chín', '30', 'g'),
(27, 'Đường phèn hạt nhỏ', '100', 'g'),
(27, 'Lá dứa thơm (lá nếp)', '3', 'nhánh'),
(28, 'Trà túi lọc hương đào', '2', 'túi'),
(28, 'Cam vàng nhập khẩu', '1', 'quả'),
(28, 'Sả nhánh đập dập', '3', 'nhánh'),
(28, 'Đào ngâm đóng hộp thái lát', '4', 'miếng'),
(28, 'Nước cốt đào ngâm', '2', 'thìa canh'),
(28, 'Mật ong nguyên chất', '1', 'thìa canh'),
(28, 'Đá viên lạnh', '1', 'ly đầy'),
(29, 'Nguyên liệu chính của món', '500', 'g'),
(29, 'Gia vị tẩm ướp cơ bản', '1', 'bộ'),
(29, 'Nước cốt dừa thơm béo', '150', 'ml'),
(29, 'Hành hoa, rau gia vị các loại', '50', 'g'),
(30, 'Nguyên liệu chính của món', '500', 'g'),
(30, 'Gia vị tẩm ướp cơ bản', '1', 'bộ'),
(30, 'Nước cốt dừa thơm béo', '150', 'ml'),
(30, 'Hành hoa, rau gia vị các loại', '50', 'g'),
(31, 'Nguyên liệu chính của món', '500', 'g'),
(31, 'Gia vị tẩm ướp cơ bản', '1', 'bộ'),
(31, 'Nước cốt dừa thơm béo', '150', 'ml'),
(31, 'Hành hoa, rau gia vị các loại', '50', 'g'),
(32, 'Nguyên liệu chính của món', '500', 'g'),
(32, 'Gia vị tẩm ướp cơ bản', '1', 'bộ'),
(32, 'Nước cốt dừa thơm béo', '150', 'ml'),
(32, 'Hành hoa, rau gia vị các loại', '50', 'g'),
(33, 'Nguyên liệu chính của món', '500', 'g'),
(33, 'Gia vị tẩm ướp cơ bản', '1', 'bộ'),
(33, 'Nước cốt dừa thơm béo', '150', 'ml'),
(33, 'Hành hoa, rau gia vị các loại', '50', 'g'),
(34, 'Nguyên liệu chính của món', '500', 'g'),
(34, 'Gia vị tẩm ướp cơ bản', '1', 'bộ'),
(34, 'Nước cốt dừa thơm béo', '150', 'ml'),
(34, 'Hành hoa, rau gia vị các loại', '50', 'g'),
(35, 'Nguyên liệu chính của món', '500', 'g'),
(35, 'Gia vị tẩm ướp cơ bản', '1', 'bộ'),
(35, 'Nước cốt dừa thơm béo', '150', 'ml'),
(35, 'Hành hoa, rau gia vị các loại', '50', 'g'),
(36, 'Nguyên liệu chính của món', '500', 'g'),
(36, 'Gia vị tẩm ướp cơ bản', '1', 'bộ'),
(36, 'Nước cốt dừa thơm béo', '150', 'ml'),
(36, 'Hành hoa, rau gia vị các loại', '50', 'g');

-- 5. Seed recipe_steps
INSERT INTO recipe_steps (recipe_id, step_number, instruction, image_url, timer_seconds)
VALUES
(1, 1, 'Sơ chế và chần xương ống bò qua nước sôi trong 10 phút để loại bỏ bọt bẩn và cặn máu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811483/mamngon/recipes/cjliyiejvfxinic7nqht.jpg', 600),
(1, 2, 'Rửa sạch xương ống bò rồi cho vào nồi cùng 5 lít nước sạch để ninh nhỏ lửa trong 6 tiếng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811521/mamngon/recipes/cen39ajhcawki9sx00ny.jpg', 600),
(1, 3, 'Nướng cháy vỏ hành tây, gừng, hành tím sau đó cạo sạch vỏ cháy và thả vào nồi nước dùng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811525/mamngon/recipes/p1uabfg63xiooexmc2lt.jpg', 600),
(1, 4, 'Rang thơm quế, hồi, thảo quả, hạt mùi bỏ vào túi lọc rồi thả vào nồi nước dùng trước khi tắt bếp 1 tiếng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811529/mamngon/recipes/waasw1cirts9uhymycom.jpg', 600),
(1, 5, 'Thịt nạm bò đem luộc chín thái mỏng, thịt thăn bò tái thái lát mỏng ngâm nước lạnh thái dẹt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811533/mamngon/recipes/tfaya37vgdmx1c88oqmp.jpg', 600),
(1, 6, 'Nêm nếm nước dùng bằng nước mắm ngon, muối hạt và đường phèn cho ngọt thanh tròn vị.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811537/mamngon/recipes/cpmubn6m5hqorinnxpxt.jpg', 600),
(1, 7, 'Chần bánh phở tươi, xếp thịt nạm, thịt tái và rắc hành mùi lên bát rồi chan nước dùng thật nóng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811542/mamngon/recipes/tdbt3ardsurlrrblzucp.jpg', 600),
(2, 1, 'Thịt ba chỉ thái lát mỏng, thịt vai xay trộn nhuyễn để làm chả miếng và chả viên.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811546/mamngon/recipes/r3iulua2doiotot8jevt.jpg', 600),
(2, 2, 'Ướp cả hai loại thịt với nước mắm, mật ong, dầu hào, hành tỏi băm nhuyễn trong 30 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812074/mamngon/recipes/rc27zpvziueqykunkrzu.jpg', 600),
(2, 3, 'Đu đủ xanh và cà rốt gọt vỏ, tỉa hoa thái mỏng bóp muối rửa sạch rồi ngâm dấm đường làm dưa góp.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811597/mamngon/recipes/dbovjfxzsdg3nonpbkzt.jpg', 600),
(2, 4, 'Nặn thịt xay thành từng viên tròn dẹt vừa ăn, xếp chả miếng lên vỉ nướng trên than hoa đến khi xém vàng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811606/mamngon/recipes/ehztzfpmhnquxgsa3wmh.jpg', 600),
(2, 5, 'Pha nước chấm chua ngọt bằng nước lọc, nước mắm, đường, dấm theo tỉ lệ 5:1:1:1 đun ấm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811613/mamngon/recipes/vrli5h1fjuveqfecw1ml.jpg', 600),
(2, 6, 'Gắp chả nóng ra bát nước chấm ấm, thêm dưa góp giòn ngọt, tỏi ớt băm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811621/mamngon/recipes/yihkvgryggquvumyn6y8.jpg', 600),
(2, 7, 'Bày bún tươi ra đĩa cùng rổ rau sống tươi ngon để ăn kèm chả nướng nóng hổi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811628/mamngon/recipes/ypky64j1vmvzo3algrmv.jpg', 600),
(3, 1, 'Rửa sạch gà ta với muối và gừng đập dập để khử mùi hôi bám ngoài da.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811646/mamngon/recipes/mxccp4tleaoj6eol62vs.jpg', 600),
(3, 2, 'Luộc gà với nước lạnh cùng hành tím đập dập, để sôi 15 phút rồi tắt bếp ngâm gà 20 phút cho chín mọng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811650/mamngon/recipes/cp4fpnqxmjyl5io9iu01.jpg', 600),
(3, 3, 'Vớt gà ra ngâm nước đá lạnh để da gà săn giòn rồi lọc lấy thịt xé miếng vừa ăn, xương bỏ lại nồi ninh tiếp.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811654/mamngon/recipes/zpmahhopfyrbnvizahwy.jpg', 600),
(3, 4, 'Nướng gừng, hành tây và rang hạt mùi cho vào nồi nước dùng ninh liu riu trong 1 tiếng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811657/mamngon/recipes/czuelveqaanyapyw8nar.jpg', 600),
(3, 5, 'Lá chanh rửa sạch thái chỉ mỏng mảnh, hành lá và rau mùi rửa sạch cắt khúc.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811695/mamngon/recipes/bwvph3doqlmbj6wru3dc.jpg', 600),
(3, 6, 'Lọc nước dùng gà qua rây cho trong veo, nêm nếm gia vị vừa miệng ăn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811699/mamngon/recipes/veo251l9lly7nhsu7isr.jpg', 600),
(3, 7, 'Xếp bánh phở chần nóng vào tô, bày thịt gà xé lên, rắc lá chanh hành mùi và chan nước dùng sôi sùng sục.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782811703/mamngon/recipes/kreqozfqmzxqfkrytgww.jpg', 600),
(4, 1, 'Chần sạch xương ống bò, bắp bò và chân giò heo cắt khúc qua nước muối gừng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815637/mamngon/recipes/zy6geoqbzdmr04hdtksc.jpg', 600),
(4, 2, 'Hòa mắm ruốc Huế vào nước lạnh gạn lấy nước trong bỏ cặn cát.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815645/mamngon/recipes/frkedxyz2veld5nibd3x.jpg', 600),
(4, 3, 'Ninh xương bò và chân giò với sả đập dập. Bắp bò luộc chín vớt ra thái lát tròn mỏng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815651/mamngon/recipes/dekiedmd6ujtnsrcyicp.jpg', 600),
(4, 4, 'Đun nóng dầu điều xào sả băm và ớt bột cho thơm rồi trút vào nồi nước dùng tạo màu đỏ óng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815658/mamngon/recipes/gli1qwdjwuwjkaoqnip0.jpg', 600),
(4, 5, 'Trút nước mắm ruốc đã gạn vào nồi nước dùng ninh cùng sả, nêm nếm gia vị đậm đà.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815664/mamngon/recipes/pizwlkbivro32rwbkjpk.jpg', 600),
(4, 6, 'Chuẩn bị rổ rau sống gồm hoa chuối bào mỏng, giá đỗ, húng quế và hành tây lát mỏng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815671/mamngon/recipes/j3indrw3gf7lxn1ljjwh.jpg', 600),
(4, 7, 'Bỏ bún sợi to chần nóng vào tô, xếp thịt bắp bò, giò khoanh, rắc hành ngò rồi chan nước dùng sả ruốc đậm đà.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815710/mamngon/recipes/bashxpk3otvlsbvxzlnf.jpg', 600),
(5, 1, 'Thịt gà ta chặt miếng nhỏ vừa ăn, ướp cùng nước mắm, hành tỏi, hạt tiêu và chút bột nghệ tạo màu sắc.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812096/mamngon/recipes/oabgh6kdnai7dj32qnmz.jpg', 600),
(5, 2, 'Củ nén nhặt sạch vỏ rễ, cho vào cối giã dập nhuyễn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812141/mamngon/recipes/tmf7xagwd18ujcsxarqs.jpg', 600),
(5, 3, 'Đun nóng dầu phộng (dầu lạc) phi củ nén vàng thơm dậy mùi đặc trưng xứ Quảng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812154/mamngon/recipes/uik5nzlt80ft9h3qswzz.jpg', 600),
(5, 4, 'Trút thịt gà đã ướp vào xào săn trên lửa lớn đến khi ngấm đều hương củ nén phi thơm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812165/mamngon/recipes/oeitqapwasyljozwjs2z.jpg', 600),
(5, 5, 'Châm nước lọc xăm xắp mặt thịt gà, rim nhỏ lửa trong 30 phút để tạo phần nước nhân sánh đậm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812176/mamngon/recipes/ftpfagil8lq1tda7dnxt.jpg', 600),
(5, 6, 'Giã dập đậu phộng đã rang vàng, bẻ bánh tráng nướng thành miếng nhỏ bày lên đĩa.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812190/mamngon/recipes/twmkzmpded6m46et1ti6.jpg', 600),
(5, 7, 'Xếp sợi mì Quảng vào tô, múc gà rim rắc lên trên, chan nước nhân xăm xắp và rắc đậu phộng, ăn kèm cải non bắp chuối.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812206/mamngon/recipes/oftcet9i9bgv2tjebmox.jpg', 600),
(6, 1, 'Ninh xương ống heo lấy nước dùng thanh ngọt, thường xuyên hớt bọt cho nước trong veo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812217/mamngon/recipes/tvtyd6pvqrw7knwwbh9f.jpg', 600),
(6, 2, 'Tôm sú đem hấp chín bóc vỏ bỏ đầu chỉ đen, trứng cút luộc chín bóc vỏ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812235/mamngon/recipes/rtmmuoyafk89qvedopnq.jpg', 600),
(6, 3, 'Gan heo luộc vừa chín thái lát mỏng, thịt heo băm đem xào săn cùng tỏi phi thơm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812251/mamngon/recipes/uaxpx0tuo3vnkekrnmd1.jpg', 600),
(6, 4, 'Tỏi băm phi vàng giòn rụm làm mỡ tỏi thơm phức.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812257/mamngon/recipes/tswnwdvlsup0pbkutci4.jpg', 600),
(6, 5, 'Sơ chế và rửa sạch lá hẹ cắt khúc ngắn, cần tây thái nhỏ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812267/mamngon/recipes/mxr5bzmtebodphituldt.jpg', 600),
(6, 6, 'Chần hủ tiếu khô qua nước sôi cho sợi hủ tiếu mềm dai tơi ngon rồi vớt ra xóc mỡ tỏi phi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812297/mamngon/recipes/rybhh6xbok0blvpksege.jpg', 600),
(6, 7, 'Xếp hủ tiếu vào tô, bày tôm, gan heo, thịt băm, trứng cút, lá hẹ hẹ và chan nước dùng ngọt lịm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812310/mamngon/recipes/wemojl1yzd8j87t0ntiz.jpg', 600),
(7, 1, 'Vo gạo tấm sạch rồi đem hấp hoặc nấu dẻo trong nồi cơm điện.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812329/mamngon/recipes/brk7o4eltsrjmcxaoir7.jpg', 600),
(7, 2, 'Sườn cốt lết heo đập nhẹ cho mềm, ướp sữa đặc, mật ong, dầu hào, tỏi băm trong 1 tiếng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812343/mamngon/recipes/du4kttqnf3nqbopohasb.jpg', 600),
(7, 3, 'Làm chả trứng: Trộn thịt băm, mộc nhĩ, bún tàu ngâm nở băm nhỏ, trứng gà (chừa 1 lòng đỏ quét mặt), đem hấp chín.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812360/mamngon/recipes/s4walyyllif3v4mcches.jpg', 600),
(7, 4, 'Da heo luộc chín thái sợi nhỏ mảnh trộn cùng thính gạo rang thơm làm bì.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812371/mamngon/recipes/iakaiblluhxh96q6sjpn.jpg', 600),
(7, 5, 'Nướng sườn trên than hoa liu riu, quét nước ướp liên tục cho sườn chín mềm mọng màu vàng óng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812376/mamngon/recipes/htufqll63tt7yclvbvqz.jpg', 600),
(7, 6, 'Làm mỡ hành bằng cách rưới dầu ăn đun sôi lên bát hành lá thái nhỏ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812386/mamngon/recipes/m6isauvaxqywbfkxwx2u.jpg', 600),
(7, 7, 'Xới cơm tấm ra đĩa, đặt miếng sườn nướng, chả trứng cắt lát, bì trộn lên, rưới mỡ hành và chan nước mắm chua ngọt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812399/mamngon/recipes/atgmqznsatmzbhadorre.jpg', 600),
(8, 1, 'Gà ta sát muối rửa sạch, luộc cùng nước lạnh, nghệ đập dập và củ hành tím cho thơm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812433/mamngon/recipes/ge977uwiornvwf83j0n6.jpg', 600),
(8, 2, 'Vớt gà chín ra để nguội, lọc thịt xé sợi vừa ăn trộn rau răm, hành tây thái mỏng, cốt chanh, muối tiêu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812449/mamngon/recipes/su0avl6dqdpb5wtidrvg.jpg', 600),
(8, 3, 'Gạo tẻ vo sạch ráo nước, xào sơ với mỡ gà và tỏi phi cho săn hạt gạo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812463/mamngon/recipes/hi0dokebgze4xjgm84xx.jpg', 600),
(8, 4, 'Dùng nước luộc gà nấu cơm để hạt cơm chín vàng bóng bẩy và dẻo ngọt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812469/mamngon/recipes/ocycpqfrsglfv3jauefd.jpg', 600),
(8, 5, 'Nấu lòng mề gà xào hành tây làm nước sốt lòng mề đậm vị.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812479/mamngon/recipes/zg2uioukf6h1d8e9uazu.jpg', 600),
(8, 6, 'Chuẩn bị rau răm nhặt lá sạch, hành tây ngâm đá lạnh khử hăng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812485/mamngon/recipes/dcp23oyuoylh3p4p9gyi.jpg', 600),
(8, 7, 'Ép cơm tấm vàng ra đĩa, xếp gà xé phay bên cạnh, rưới mỡ hành, nước sốt lòng gà ấm áp.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812492/mamngon/recipes/bbnalwckizxedat9yuuc.jpg', 600),
(9, 1, 'Cá lóc làm sạch màng đen cặn máu trong bụng, rửa qua nước dấm pha muối để khử nhớt hôi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812498/mamngon/recipes/dmalsvn3hbpl8fdctt7x.jpg', 600),
(9, 2, 'Ướp cá với nước màu thốt nốt, nước mắm, hành tỏi băm, hạt nêm và hạt tiêu trong 30 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812503/mamngon/recipes/pwt6gb9fmnt8u2gss5sd.jpg', 600),
(9, 3, 'Thịt ba chỉ heo thái miếng nhỏ mỏng vừa ăn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812509/mamngon/recipes/majngkyylakih2qw7kn8.jpg', 600),
(9, 4, 'Xếp thịt ba chỉ xuống đáy tộ đất để chống cháy khét khi kho lâu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812537/mamngon/recipes/g7wa95ijwrs8fqurl45h.jpg', 600),
(9, 5, 'Đặt các khúc cá lóc lên trên, đổ nước ướp cá và nước dừa tươi vào nồi ngập xăm xắp.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812543/mamngon/recipes/w64evi78gtug5gi3exwu.jpg', 600),
(9, 6, 'Kho cá trên lửa lớn đến khi sôi bùng thì hạ nhỏ lửa đun liu riu cho nước cạn sền sệt, cá ngấm sậm màu caramel.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812555/mamngon/recipes/hoknnpeaogalga45qqzv.jpg', 600),
(9, 7, 'Rắc thêm ớt hiểm đỏ, hành lá thái nhỏ và tiêu đen xay giã dập thơm nức trước khi tắt bếp.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812561/mamngon/recipes/jeb7v7teqaxqvj9qbhqq.jpg', 600),
(10, 1, 'Cá lóc làm sạch cắt khúc dày khoảng 2cm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815761/mamngon/recipes/ibyifoybixk9s2tqowck.jpg', 600),
(10, 2, 'Tước vỏ dọc mùng rửa sạch thái vạt chéo, đậu bắp thái xéo, dứa thái miếng nhỏ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815768/mamngon/recipes/y6fxdnhnca5qesh1q2cy.jpg', 600),
(10, 3, 'Đun sôi 1.5 lít nước sạch rồi trút nước cốt me chua vào để tạo vị chua nền.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815774/mamngon/recipes/q4dmav8cvbrkbmg1e2ek.jpg', 600),
(10, 4, 'Thả cá lóc cắt khúc vào nấu chín tới rồi vớt cá ra dĩa riêng để cá không bị nát.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815780/mamngon/recipes/zu7x3n0t6lpsska8detm.jpg', 600),
(10, 5, 'Trút cà chua, dứa nấu chín rồi thêm đậu bắp, dọc mùng, giá đỗ đun sôi bùng lại.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815838/mamngon/recipes/mf7vzdpxrgce9u2ogbar.jpg', 600),
(10, 6, 'Nêm nếm canh bằng đường phèn, muối hạt và nước mắm cho vị chua ngọt dịu dễ chịu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815845/mamngon/recipes/m26nrzm7asclfsczadr1.jpg', 600),
(10, 7, 'Múc canh ra tô lớn, xếp cá lên, rắc rau om ngò gai cắt nhỏ và vài lát ớt hiểm chín.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815853/mamngon/recipes/wy1r1xivzgeoysbrwgdx.jpg', 600),
(11, 1, 'Hòa cua đồng xay với nước lọc gạn lấy nước thịt cua qua rây nhiều lần.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812678/mamngon/recipes/bxqdnqkptbnfqrqakwnp.jpg', 600),
(11, 2, 'Đun nước lọc cua với chút muối nhỏ lửa, khuấy nhẹ tay cho riêu cua đông kết thành tảng rồi vớt ra.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812696/mamngon/recipes/fml8ppveqy3kddr4ihqp.jpg', 600),
(11, 3, 'Đậu hũ thái miếng nhỏ chiên vàng giòn rụm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812703/mamngon/recipes/wa435slxlubaug0mkkln.jpg', 600),
(11, 4, 'Phi thơm hành khô, xào cà chua bổ múi cau tạo màu nước lèo đỏ hồng tự nhiên.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812711/mamngon/recipes/ul8cwnqqasqjnwdvnwjp.jpg', 600),
(11, 5, 'Thêm dấm bỗng và thìa mắm tôm vào nước dùng cua cho dậy mùi thơm chua thanh tao.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812723/mamngon/recipes/fhovmuu6rtjaww78mwhn.jpg', 600),
(11, 6, 'Thịt bắp bò hoa thái mỏng đem chần nhanh chín tái trong nồi nước dùng đang sôi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812729/mamngon/recipes/wdtuzspszou5cgxotjgd.jpg', 600),
(11, 7, 'Xếp bún vào tô, bày miếng riêu cua xốp, đậu hũ chiên, thịt bò chần ngập hành ngò chan nước chua ngọt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812735/mamngon/recipes/gfjhuck8lvvvswhmm6og.jpg', 600),
(12, 1, 'Ốc luộc chín khều lấy thịt rửa sạch bằng dấm muối cho sạch nhớt rồi thái nhỏ xào thơm hành tỏi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812775/mamngon/recipes/m1cw1dbvu0qein4cjoal.jpg', 600),
(12, 2, 'Thịt ba chỉ heo thái miếng con chì vừa ăn rang cháy cạnh ngấm gia vị nghệ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812784/mamngon/recipes/one21ebw03inrtbfnabz.jpg', 600),
(12, 3, 'Đậu phụ thái khối vuông nhỏ chiên vàng giòn các mặt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812793/mamngon/recipes/c241bpvxr4appzctw7s3.jpg', 600),
(12, 4, 'Chuối xanh tước vỏ cắt khúc chẻ tư ngâm nước dấm loãng tránh thâm đen.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812803/mamngon/recipes/idt4g8klolaqtluasmwr.jpg', 600),
(12, 5, 'Hầm chuối xanh với bột nghệ và nước dùng mắm tôm cho chuối mềm bùi sánh.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812826/mamngon/recipes/np6vwumnsiktokmfeidy.jpg', 600),
(12, 6, 'Trút thịt ba chỉ, đậu phụ rán chín vào nồi hầm chuối đun nhỏ lửa 15 phút, nêm dấm bỗng thơm chua.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812831/mamngon/recipes/w0br2fgosl3kjzyqgzzq.jpg', 600),
(12, 7, 'Cho ốc nhồi đã xào vào nồi, rắc lá lốt tía tô xắt nhỏ đun sôi rồi múc canh ra bát.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812837/mamngon/recipes/yvzbfxatk3kgestezb3f.jpg', 600),
(13, 1, 'Ninh xương heo kỹ lấy nước dùng, gạn bọt liên tục để nước súp ngọt trong.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812843/mamngon/recipes/rwb4fclhihdtaiyhwcnl.jpg', 600),
(13, 2, 'Xào qua thịt cua bể với dầu điều, tỏi phi cho thơm dậy gạch cua màu vàng óng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812849/mamngon/recipes/qomue7bayvb8r45ctppy.jpg', 600),
(13, 3, 'Pha bột năng với chút nước lọc khuấy tan thả nhẹ vào nồi súp đun sánh nhẹ quyến rũ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812859/mamngon/recipes/nvfjyqxikoin5uibgase.jpg', 600),
(13, 4, 'Trút thịt cua bể xào thơm vào nồi nước dùng đun nhỏ lửa nêm nếm muối đường.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812889/mamngon/recipes/ykswc2uxis2y5cyj2xaf.jpg', 600),
(13, 5, 'Bánh canh chần chín dẻo mềm xóc qua nước lạnh cho sợi không bị dính.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812895/mamngon/recipes/zchbj8dxpar0djxs51ip.jpg', 600),
(13, 6, 'Cắt nhỏ hành lá hẹ tươi ngò gai bày đĩa riêng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812901/mamngon/recipes/s4hp6y0rqi5sxadzaavv.jpg', 600),
(13, 7, 'Múc sợi bánh canh ra bát lớn, chan nước súp cua sánh đỏ đặc sánh rắc tiêu thơm nồng hành phi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812907/mamngon/recipes/f1cknn0q8shlgxezpc8s.jpg', 600),
(14, 1, 'Tôm rửa sạch bỏ chỉ lưng, mực thái khoanh hoa, nghêu ngâm ớt cho nhả sạch cát.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812913/mamngon/recipes/avejf0ctabicn3fy6di0.jpg', 600),
(14, 2, 'Đập dập sả nhánh cắt khúc, riềng thái lát mỏng, lá chanh vò nhẹ cho thơm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812954/mamngon/recipes/aj5m8gxx3uy7m0tihspt.jpg', 600),
(14, 3, 'Nấu sôi nước dùng xương heo rồi thả sả, riềng, lá chanh đun sôi 10 phút dậy hương.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812961/mamngon/recipes/hsdhx6ssq0yov66klj0n.jpg', 600),
(14, 4, 'Trút gói sốt Tom Yum lẩu Thái vào khuấy tan cho nước lẩu chuyển màu cam sậm bắt mắt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812967/mamngon/recipes/ryrmvlu0uq68qk28stv9.jpg', 600),
(14, 5, 'Nêm nếm gia vị chua cay hài hòa thơm nước cốt chanh.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812973/mamngon/recipes/bydhz2mzpolnuexpxwue.jpg', 600),
(14, 6, 'Xếp hải sản ra đĩa tròn xếp nấm xung quanh bàn tiệc lẩu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812980/mamngon/recipes/corxyaxlic5lbsikrk4x.jpg', 600),
(14, 7, 'Đặt nồi lẩu lên bếp bàn ăn đun sôi sùng sục thả dần hải sản nấm ăn kèm bún tươi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812987/mamngon/recipes/j9usuxidsdzww5hvhkvr.jpg', 600),
(15, 1, 'Đậu hũ trắng rửa nhẹ tránh nát thái miếng vuông vừa ăn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782812998/mamngon/recipes/hpiebmgk8p7po2v302qe.jpg', 600),
(15, 2, 'Cà chua chín bỏ cuống rửa sạch thái lựu nhỏ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813007/mamngon/recipes/vmw9g9oiq3utvlnjdmr7.jpg', 600),
(15, 3, 'Chiên đậu hũ trong dầu nóng lửa vừa đến khi lớp vỏ ngoài vàng ruộm dai mềm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813033/mamngon/recipes/gozvdwuvg8rqufshkxnp.jpg', 600),
(15, 4, 'Hành boaro thái nhỏ phi thơm trên chảo dầu nóng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813041/mamngon/recipes/scwfyxquqyvzxuelz0sc.jpg', 600),
(15, 5, 'Trút cà chua thái lựu vào xào nhuyễn cùng chút nước lọc tạo nước sốt đỏ sệt mịn màng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813047/mamngon/recipes/ukeciyu2ipwhank0pq3h.jpg', 600),
(15, 6, 'Nêm nước tương, muối và hạt nêm chay nấm vào sốt cà chua đun nhỏ lửa.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813053/mamngon/recipes/ggvqpgfnodkn4yzou1ku.jpg', 600),
(15, 7, 'Thả đậu hũ rán vàng vào sốt cà chua đun lim rim 10 phút cho đậu ngấm đẫm gia vị rồi rắc hành ngò lên.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813061/mamngon/recipes/t4e8hjt6vzvrrfmjkfwd.jpg', 600),
(16, 1, 'Thịt ba chỉ luộc chín cùng chút muối hành đập dập vớt ra ngâm đá lạnh thái mỏng dài.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813092/mamngon/recipes/hddsq7yc2kr3xvt7tdwf.jpg', 600),
(16, 2, 'Tôm sú luộc chín bóc vỏ chẻ đôi lưng lấy chỉ đen bỏ đầu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813098/mamngon/recipes/ah5itbcm7l27e6yonvyj.jpg', 600),
(16, 3, 'Rau thơm xà lách rửa sạch ngâm nước muối loãng vẩy ráo nước.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813104/mamngon/recipes/t9yphaikfufkxaus4axk.jpg', 600),
(16, 4, 'Làm nước chấm: Xào tương ngọt với tỏi băm bơ đậu phộng và chút nước lọc đun ấm sánh.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813111/mamngon/recipes/grjsxxzs0z3v9q0lmamd.jpg', 600),
(16, 5, 'Trải bánh tráng phẳng thấm chút nước cho mềm dai dễ cuốn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813121/mamngon/recipes/hv57s3hqw80sc1lcdyb4.jpg', 600),
(16, 6, 'Xếp xà lách, rau thơm, bún tươi, thịt heo luộc và hẹ ló ngọn ra ngoài.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813135/mamngon/recipes/aw1rrjkmuxjdgxnnag6l.jpg', 600),
(16, 7, 'Cuốn chặt tay nửa vòng rồi xếp tôm đỏ ở mặt ngoài cuộn tròn lại bày đĩa ăn kèm sốt tương hạt dẻ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813173/mamngon/recipes/ohzldohuuknbueor9wpu.jpg', 600),
(17, 1, 'Thịt bò thăn thái khối vuông nhỏ 2x2cm, ướp tỏi băm dầu hào hạt tiêu đường trong 30 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813180/mamngon/recipes/b8n7wa5cbzren3vnteqy.jpg', 600),
(17, 2, 'Ớt chuông hành tây cắt miếng vuông tương đương kích thước miếng bò lúc lắc.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813188/mamngon/recipes/l6ob4vst3bs1lws9em0u.jpg', 600),
(17, 3, 'Khoai tây cắt que ngâm nước muối chiên vàng giòn ráo dầu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813196/mamngon/recipes/ilxftuwjqcrztgrpmccx.jpg', 600),
(17, 4, 'Đun nóng chảo dầu phi thơm tỏi băm xào nhanh ớt chuông hành tây chín tới đổ đĩa riêng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814141/mamngon/recipes/jsdrezie1tlemtxfuwu0.jpg', 600),
(17, 5, 'Bật chảo thật nóng lửa to cho chút dầu ăn bơ lạt vào xào thịt bò lắc mạnh chảo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813257/mamngon/recipes/zdt5ab8tcdxbsgijjf4h.jpg', 600),
(17, 6, 'Trút hỗn hợp ớt chuông hành tây đã xào vào chảo bò đảo đều 2 phút nêm dầu hào.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813273/mamngon/recipes/xkwnszhsd7laufdcckn0.jpg', 600),
(17, 7, 'Trình bày bò lúc lắc nóng hổi ra đĩa lớn bên cạnh khoai tây chiên giòn chấm muối tiêu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813290/mamngon/recipes/z6j8klj8lqkpkt6gvc82.jpg', 600),
(18, 1, 'Nấm đùi gà cắt chân ngâm nước muối loãng 10 phút rửa sạch cắt lát xéo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813306/mamngon/recipes/ppkutaogmm3gxudwrvrc.jpg', 600),
(18, 2, 'Tiêu xanh dùng cán dao đập dập nhẹ vài hạt để tiết hương thơm ấm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813322/mamngon/recipes/ixi5l5isoxq51tdfvdz1.jpg', 600),
(18, 3, 'Ướp nấm đùi gà với nước tương, đường mía, nước màu dừa chay trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813339/mamngon/recipes/pdydkaxd3d5plllf41a8.jpg', 600),
(18, 4, 'Phi thơm hành boaro băm nhuyễn với chút dầu ăn thực vật.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813350/mamngon/recipes/bgi1odgqyq6lsvathy1n.jpg', 600),
(18, 5, 'Trút nấm đùi gà và chùm tiêu xanh vào nồi kho đất đun lửa lớn sôi bùng lên.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813374/mamngon/recipes/w3tuslss0vjldwagbha8.jpg', 600),
(18, 6, 'Hạ lửa nhỏ liu riu kho nấm đùi gà thấm sậm màu nâu bóng ngấm vị cay tiêu xanh.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813380/mamngon/recipes/obl3sdfnxwjpbqkli0ad.jpg', 600),
(18, 7, 'Khi nước kho sền sệt keo lại thả ớt cắt lát rắc thêm tiêu đen giã dập ấm áp.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813386/mamngon/recipes/mi38xw59uj56tunx1btl.jpg', 600),
(19, 1, 'Thịt ba chỉ rửa sạch thái miếng vuông dày khoảng 3-4cm dẹt thịt kho tàu.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814168/mamngon/recipes/eda9nvkmlp9cluo0gsse.jpg', 600),
(19, 2, 'Ướp thịt với nước mắm ngon, nước màu caramen, tỏi hành băm nhuyễn và tiêu bột trong 40 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813450/mamngon/recipes/qwu06gneiwg0xjreolec.jpg', 600),
(19, 3, 'Trứng cút luộc chín bóc vỏ chiên sơ qua dầu nóng để lớp da trứng dai dai (tùy sở thích).', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813465/mamngon/recipes/bn9pggqwk8gwrz22ui68.jpg', 600),
(19, 4, 'Đảo thịt ba chỉ đã ướp trên lửa lớn cho săn mỡ thịt rút khô gia vị.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814191/mamngon/recipes/p8caruvzwbk1gitooz5z.jpg', 600),
(19, 5, 'Đổ toàn bộ nước dừa tươi xiêm vào nồi ngập thịt đun sôi bùng hớt sạch bọt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813485/mamngon/recipes/wzjnzqgz9hdld4bj9hvp.jpg', 600),
(19, 6, 'Hạ lửa nhỏ liu riu đậy hờ vung kho thịt trong 1 tiếng cho thịt chín mềm nhừ tự nhiên.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813531/mamngon/recipes/frcr44kgyut1ejninqmu.jpg', 600),
(19, 7, 'Thả trứng cút vào kho cùng đun tiếp 15 phút đến khi thịt và trứng thấm màu cánh gián ngọt đà.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813548/mamngon/recipes/co2znyakheshihsd723g.jpg', 600),
(20, 1, 'Thịt đùi gà ta rửa sạch chặt miếng vuông vừa ăn ráo nước.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813562/mamngon/recipes/hyg7emp3slnn1q4tuiiz.jpg', 600),
(20, 2, 'Ướp gà với nước mắm, đường dừa, hành băm và một nửa gừng thái sợi trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813575/mamngon/recipes/tcjowxs1ax3kn39erizq.jpg', 600),
(20, 3, 'Đun nóng dầu ăn phi thơm củ hành băm xắt mỏng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813584/mamngon/recipes/pqcjhsivrotxeswdhdda.jpg', 600),
(20, 4, 'Cho thịt gà vào xào săn đều lửa lớn cho da gà săn vàng thơm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813592/mamngon/recipes/vsplq1vp4vg7xo6hnvo3.jpg', 600),
(20, 5, 'Trút gừng thái sợi còn lại vào chảo cùng chút nước ấm kho nhỏ lửa.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813598/mamngon/recipes/jwdr6ibirmerr6ncvlwz.jpg', 600),
(20, 6, 'Đậy vung kho gà liu riu đun 20 phút đến khi gà chín mềm thấm đượm vị gừng ấm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813621/mamngon/recipes/pmyiu0yha0i6aggxhs5g.jpg', 600),
(20, 7, 'Mở vung đun cạn bớt nước kho nêm hành lá thái khúc tiêu bột dọn đĩa.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813634/mamngon/recipes/v3yfjckabba1f1q4ghxd.jpg', 600),
(21, 1, 'Mực ống làm sạch ruột mắt cắt khoanh tròn khía nhẹ hoa cúc trên thân mực.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813648/mamngon/recipes/chfozsvmemiqppl2uygu.jpg', 600),
(21, 2, 'Chần nhanh mực qua nước sôi pha gừng đập dập 5 giây vớt ra ngâm đá lạnh giữ độ giòn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814209/mamngon/recipes/adkdoy3e866p7ulyshg3.jpg', 600),
(21, 3, 'Ớt chuông và hành tây thái lát chéo múi cau.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813696/mamngon/recipes/ylvok2smdakysayvidpv.jpg', 600),
(21, 4, 'Phi thơm tỏi băm trên chảo dầu nóng xào sa tế tôm cay dậy mùi đỏ hồng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813718/mamngon/recipes/xt37wrsaj1jwign3kqtp.jpg', 600),
(21, 5, 'Cho ớt chuông hành tây vào xào nhanh lửa lớn chín tái.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814228/mamngon/recipes/mee5rybzillzcbdioy6e.jpg', 600),
(21, 6, 'Trút mực ống chín tái vào chảo đảo thật nhanh tay lửa lớn 3 phút bọc đều sa tế.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814255/mamngon/recipes/lsqvqjkfvycsbz92dzss.jpg', 600),
(21, 7, 'Nêm dầu hào nước mắm ngon hành lá tiêu bột giã dập đổ đĩa nóng hổi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813746/mamngon/recipes/lekrddznllwsiojmavf1.jpg', 600),
(22, 1, 'Ninh xương ống heo lấy nước súp ngọt trong hớt bọt thật kỹ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813759/mamngon/recipes/zrtjaev3yr7bmn23yth2.jpg', 600),
(22, 2, 'Sườn sụn non rửa sạch cắt miếng nhỏ chần qua rồi hầm chín mềm rục thịt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813772/mamngon/recipes/h4qfu9gwvejawbkew5yg.jpg', 600),
(22, 3, 'Hòa bột gạo tẻ với nước hầm xương nguội khuấy tan hoàn toàn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813787/mamngon/recipes/vpjhomcn4xn33xx8fpwr.jpg', 600),
(22, 4, 'Đun nồi cháo bột gạo trên lửa nhỏ khuấy liên tục đều tay tránh khê bén đáy nồi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813831/mamngon/recipes/pfftzxotxhmk1dar1uto.jpg', 600),
(22, 5, 'Trút sườn sụn hầm chín mềm vào nồi cháo khuấy cùng đun tiếp cho sánh mượt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814302/mamngon/recipes/zkpfukvfrxy8a5yf1tvb.jpg', 600),
(22, 6, 'Nêm nếm gia vị hạt nêm nước mắm ngon muối vừa vị cháo Hà Nội.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814375/mamngon/recipes/fmma85ndqs4zmc21paev.jpg', 600),
(22, 7, 'Múc cháo sườn sánh nóng ra bát rắc ruốc thịt hành phi hạt tiêu bẻ quẩy giòn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782813857/mamngon/recipes/ktczwpe1s8lue0aapieq.jpg', 600),
(23, 1, 'Pha bột bánh xèo với nước lọc cốt dừa béo hành lá thái nhỏ để nghỉ bột 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814384/mamngon/recipes/uedbcjeqd6vjknnyvaau.jpg', 600),
(23, 2, 'Tôm ba chỉ xào sơ cùng hành tây nêm muối tiêu chín tái.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814393/mamngon/recipes/vnwwrzaannqwepgxo3dl.jpg', 600),
(23, 3, 'Làm nóng chảo lớn quét mỡ đều láng chảo thật nóng xèo xèo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814402/mamngon/recipes/klobhojnnhntm3x4eea7.jpg', 600),
(23, 4, 'Múc muôi bột bánh xèo láng tròn mỏng quanh lòng chảo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814437/mamngon/recipes/rmxxoxjqvw0qpjdfji0q.jpg', 600),
(23, 5, 'Rải nhân tôm ba chỉ giá đỗ vào một bên đậy vung chảo 2 phút cho bánh chín.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814448/mamngon/recipes/zq58egcxymrcyhy6mlkd.jpg', 600),
(23, 6, 'Mở vung đun tiếp chảo nhỏ lửa cho vỏ bánh vàng giòn gập đôi bánh xèo lại.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814454/mamngon/recipes/jwp7amjwzkajymymf8qr.jpg', 600),
(23, 7, 'Cho bánh ra dĩa cắt đôi ăn cuốn cải bẹ xanh rau thơm chấm nước mắm tỏi ớt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814460/mamngon/recipes/mkaf2an7tcg3hl7xxsde.jpg', 600),
(24, 1, 'Bóp trộn cơm nguội với 2 lòng đỏ trứng gà tạo màu vàng óng bọc đều hạt cơm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814468/mamngon/recipes/gr6cvjbdkswg77iimibd.jpg', 600),
(24, 2, 'Luộc sơ đậu Hà Lan bắp ngọt thái hạt lựu tôm mực cho chín tái.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814483/mamngon/recipes/lkxdgj0z561qdsvsprrp.jpg', 600),
(24, 3, 'Phi thơm tỏi băm xào săn tôm mực hải sản rau củ nêm gia vị xúc ra đĩa.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814492/mamngon/recipes/vtuwqnctt4oukam8lx0l.jpg', 600),
(24, 4, 'Dùng chảo nóng chiên cơm trứng liên tục đều tay cho hạt cơm săn khô tơi bóng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814501/mamngon/recipes/x7yxgdipmqzlaavaqgwj.jpg', 600),
(24, 5, 'Trút đĩa tôm mực rau củ vào cơm đảo đều tay nêm nước tương ngon muối nhạt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814509/mamngon/recipes/ibemeeqoeadqteqbxmw4.jpg', 600),
(24, 6, 'Khoét rỗng quả dừa xiêm bày cơm chiên nóng hổi vào lòng quả dừa.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814546/mamngon/recipes/bk9s6hzib7iznnhwad3m.jpg', 600),
(24, 7, 'Đặt dừa nướng lò hoặc hấp nóng 5 phút dậy mùi cơm dừa béo ngậy thơm dẻo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814555/mamngon/recipes/gtj47adpyojtiqbgsqfm.jpg', 600),
(25, 1, 'Luộc mì Ý trong nước sôi pha chút muối trong 8-10 phút cho mì chín mềm dẻo vừa (Al dente) rồi vớt ráo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814563/mamngon/recipes/kyzgrwjymklgg3jdeeas.jpg', 600),
(25, 2, 'Phi thơm tỏi băm tây hạt lựu với dầu ô-liu bơ lạt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814572/mamngon/recipes/xxoss0l38jlvwjzhugpm.jpg', 600),
(25, 3, 'Cho thịt bò băm nhuyễn vào xào chín săn nêm tiêu muối.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814581/mamngon/recipes/ludevhnu0yvoig1oiqjz.jpg', 600),
(25, 4, 'Trút cà chua xay mịn vào chảo xào nhuyễn hầm nhỏ lửa cùng thịt bò thành nước sốt sệt đỏ.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814617/mamngon/recipes/kph3w7nmrretw1j2jbje.jpg', 600),
(25, 5, 'Rắc lá oregano khô thơm vào nước sốt hầm nhỏ lửa 15 phút dậy mùi thơm mì Ý.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814628/mamngon/recipes/i1b90dwgnwmef3noplfq.jpg', 600),
(25, 6, 'Xếp sợi mì Ý ấm nóng cuộn tròn dĩa lớn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814670/mamngon/recipes/cylg21tiw9kk2vwdmjaj.jpg', 600),
(25, 7, 'Múc sốt bò bằm đậm đà chan lên đĩa mì rắc bột phô mai Parmesan bột ăn nóng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814679/mamngon/recipes/no6ddpxh80td0a6kxeqk.jpg', 600),
(26, 1, 'Đậu hũ chiên cắt sợi dọc dài.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814689/mamngon/recipes/pmywrdbpxu8n9cznszhb.jpg', 600),
(26, 2, 'Rửa sạch cà rốt dưa leo gọt vỏ bào sợi mỏng dài dưa leo bỏ ruột.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814697/mamngon/recipes/vepf8mlqi2wkfsaxtocd.jpg', 600),
(26, 3, 'Bơ sáp lột vỏ thái lát mỏng dẹt dẻo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814706/mamngon/recipes/vr5fgsduirodqthswiu2.jpg', 600),
(26, 4, 'Làm nước sốt bơ lạc: Trộn bơ đậu phộng xíu nước tương ớt xay đường nước ấm khuấy mịn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814733/mamngon/recipes/j3xw8ios4alpochvqzfi.jpg', 600),
(26, 5, 'Làm ẩm nhẹ bánh tráng cuộn dẻo bằng khăn ấm lướt qua.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814743/mamngon/recipes/zo72ore8nsyrvjyb2kbo.jpg', 600),
(26, 6, 'Xếp lá xà lách cải non sợi cà rốt dưa leo bún tươi lát bơ sáp vàng ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814752/mamngon/recipes/y0vywmtgcvyednjempvs.jpg', 600),
(26, 7, 'Cuốn bánh tráng chặt tay cuộn tròn dài bắt mắt cắt đôi bày đĩa tương bơ phộng ngọt ngào.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814761/mamngon/recipes/rrf1f53dwjgjugbxnsiw.jpg', 600),
(27, 1, 'Ngâm bột Gelatin nở trong nước lạnh 15 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814768/mamngon/recipes/lwcp4ui4zqwthbfqqkvg.jpg', 600),
(27, 2, 'Đun ấm hỗn hợp sữa tươi kem tươi đường cát không sôi bùng thả gelatin khuấy tan chảy hết.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814776/mamngon/recipes/hh62eigfz6jerfqd8guo.jpg', 600),
(27, 3, 'Đổ sữa gelatin vào khuôn vuông để ngăn đông lạnh mát ít nhất 4 tiếng đông dẻo.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814784/mamngon/recipes/ht0hncebytl8hqwsstkc.jpg', 600),
(27, 4, 'Nhãn xuồng bóc vỏ dùng dao khéo léo tách hạt tròn đẹp.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814813/mamngon/recipes/h4ypyxuoz2j60av2v6dp.jpg', 600),
(27, 5, 'Đun nước đường phèn cùng lá dứa thơm đun sôi 10 phút thả nhãn tươi chần qua tắt bếp làm lạnh.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814821/mamngon/recipes/i7j43u4nkxoq03anf1qt.jpg', 600),
(27, 6, 'Cắt thạch khúc bạch đông cứng thành miếng hình ô cờ đẹp mắt.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814866/mamngon/recipes/o3e88yrub9kpefzcct4z.jpg', 600),
(27, 7, 'Xếp khúc bạch vào chén bày nhãn cùi dày rưới nước đường phèn rắc hạnh nhân rang giòn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814875/mamngon/recipes/p0kzxwwmoj4o9ej6v89q.jpg', 600),
(28, 1, 'Sả rửa sạch đập dập cắt khúc đun sôi với 300ml nước lọc trong 5 phút thơm nồng.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814883/mamngon/recipes/kexc7clbogf2yeark5m9.jpg', 600),
(28, 2, 'Dùng nước sả nóng hãm 2 túi lọc trà đào trong 10 phút ráo bã.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814892/mamngon/recipes/avfqvkddmr5qrb8vqfji.jpg', 600),
(28, 3, 'Cắt đôi quả cam vàng vắt nước một nửa, nửa còn lại thái lát tròn mỏng bày ly.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814911/mamngon/recipes/pihq8slja5bkjxs2qyd2.jpg', 600),
(28, 4, 'Hòa nước trà sả thơm với nước cam vắt mật ong nước đào hộp khuấy đều.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814919/mamngon/recipes/nhrzzuqioidu0la439vy.jpg', 600),
(28, 5, 'Thái lát đào ngâm vừa ăn.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814928/mamngon/recipes/uhq2yfbwwd3hppry7vum.jpg', 600),
(28, 6, 'Cho đá viên lạnh vào ly thủy tinh rót nước trà đào cam sả óng vàng lên.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814937/mamngon/recipes/wuzgm29ahyyozlkbnlyq.jpg', 600),
(28, 7, 'Trang trí lát đào ngâm đào miếng hành ngò trang trí lát cam vàng lá sả tươm thơm mát.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814945/mamngon/recipes/mujzmm3i551n2ytuotry.jpg', 600),
(29, 1, 'Chuẩn bị và sơ chế sạch sẽ các nguyên liệu cho món Cà ri gà nước cốt dừa.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782814988/mamngon/recipes/fktj73eq1ljhavifbp8n.jpg', 600),
(29, 2, 'Ướp nguyên liệu với gia vị vừa miệng đun sôi trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815000/mamngon/recipes/pviuuehmghnlqdpnfas9.jpg', 600),
(29, 3, 'Hầm nhỏ lửa cho gia vị ngấm đều đậm đà thơm ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815010/mamngon/recipes/sjg4wfjkzopuyewbgztw.jpg', 600),
(29, 4, 'Thêm nước cốt dừa tươi hoặc các loại topping đi kèm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815027/mamngon/recipes/utugyxe2zxghr0b3qfnl.jpg', 600),
(29, 5, 'Múc món ăn ra tô dĩa trang trí bày lên bàn ăn dùng nóng cực ngon.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815034/mamngon/recipes/o0wcc6nzhev7a421yhj6.jpg', 600),
(30, 1, 'Chuẩn bị và sơ chế sạch sẽ các nguyên liệu cho món Bánh xèo miền Tây.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815042/mamngon/recipes/m7cf3dxd5omwx5117hja.jpg', 600),
(30, 2, 'Ướp nguyên liệu với gia vị vừa miệng đun sôi trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815049/mamngon/recipes/komoxagqvpo9ytj5dgab.jpg', 600),
(30, 3, 'Hầm nhỏ lửa cho gia vị ngấm đều đậm đà thơm ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815055/mamngon/recipes/vje9sd66iplokoow2szy.jpg', 600),
(30, 4, 'Thêm nước cốt dừa tươi hoặc các loại topping đi kèm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815095/mamngon/recipes/z7bvlqsugaoryaxftt46.jpg', 600),
(30, 5, 'Múc món ăn ra tô dĩa trang trí bày lên bàn ăn dùng nóng cực ngon.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815102/mamngon/recipes/mztjs1r4ff3yixi39aft.jpg', 600),
(31, 1, 'Chuẩn bị và sơ chế sạch sẽ các nguyên liệu cho món Sushi cuộn cá hồi Na Uy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815110/mamngon/recipes/tkqkgcasdz94p5hmoyqe.jpg', 600),
(31, 2, 'Ướp nguyên liệu với gia vị vừa miệng đun sôi trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815116/mamngon/recipes/flwg11afmypplwph0mzt.jpg', 600),
(31, 3, 'Hầm nhỏ lửa cho gia vị ngấm đều đậm đà thơm ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815123/mamngon/recipes/giaqby4zwxzsjhbwhckt.jpg', 600),
(31, 4, 'Thêm nước cốt dừa tươi hoặc các loại topping đi kèm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815130/mamngon/recipes/wbhbpm09hn3q2czztqhi.jpg', 600),
(31, 5, 'Múc món ăn ra tô dĩa trang trí bày lên bàn ăn dùng nóng cực ngon.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815155/mamngon/recipes/gswe0vaohnxdxslcj9dj.jpg', 600),
(32, 1, 'Chuẩn bị và sơ chế sạch sẽ các nguyên liệu cho món Tokbokki bánh gạo phô mai.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815163/mamngon/recipes/atiibfq8g68tumsbcy7u.jpg', 600),
(32, 2, 'Ướp nguyên liệu với gia vị vừa miệng đun sôi trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815200/mamngon/recipes/it7kejsid56raudigj4z.jpg', 600),
(32, 3, 'Hầm nhỏ lửa cho gia vị ngấm đều đậm đà thơm ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815208/mamngon/recipes/pfqmssthw5yn4dbyhi5j.jpg', 600),
(32, 4, 'Thêm nước cốt dừa tươi hoặc các loại topping đi kèm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815216/mamngon/recipes/y72wpm7eoocp9ewlff6n.jpg', 600),
(32, 5, 'Múc món ăn ra tô dĩa trang trí bày lên bàn ăn dùng nóng cực ngon.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815224/mamngon/recipes/ymdpabln6znbfg4nygbj.jpg', 600),
(33, 1, 'Chuẩn bị và sơ chế sạch sẽ các nguyên liệu cho món Chè đậu xanh cốt dừa.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815245/mamngon/recipes/qz9otb44skiiznke7gwf.jpg', 600),
(33, 2, 'Ướp nguyên liệu với gia vị vừa miệng đun sôi trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815252/mamngon/recipes/a9ul95yrasmlnjowtka1.jpg', 600),
(33, 3, 'Hầm nhỏ lửa cho gia vị ngấm đều đậm đà thơm ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815259/mamngon/recipes/k4updxvcqk45nsroevek.jpg', 600),
(33, 4, 'Thêm nước cốt dừa tươi hoặc các loại topping đi kèm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815265/mamngon/recipes/ubbswphnf5yh2w1a3ro0.jpg', 600),
(33, 5, 'Múc món ăn ra tô dĩa trang trí bày lên bàn ăn dùng nóng cực ngon.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815272/mamngon/recipes/w0fcnvitwa60hwpzwgj4.jpg', 600),
(34, 1, 'Chuẩn bị và sơ chế sạch sẽ các nguyên liệu cho món Xôi xoài cốt dừa Thái.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815282/mamngon/recipes/ugswpmfyadqkwnjmcpwi.jpg', 600),
(34, 2, 'Ướp nguyên liệu với gia vị vừa miệng đun sôi trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815304/mamngon/recipes/htflw5nhzph5puvdh2nb.jpg', 600),
(34, 3, 'Hầm nhỏ lửa cho gia vị ngấm đều đậm đà thơm ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815311/mamngon/recipes/bi5nkf7rcsdlyaka07ep.jpg', 600),
(34, 4, 'Thêm nước cốt dừa tươi hoặc các loại topping đi kèm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815349/mamngon/recipes/umpacxcnkaoiplww2gjf.jpg', 600),
(34, 5, 'Múc món ăn ra tô dĩa trang trí bày lên bàn ăn dùng nóng cực ngon.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815356/mamngon/recipes/ciixvrllq9tjmb17kmhq.jpg', 600),
(35, 1, 'Chuẩn bị và sơ chế sạch sẽ các nguyên liệu cho món Sữa chua nếp cẩm dẻo bùi.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815393/mamngon/recipes/lufjolnv9dulofp5fftv.jpg', 600),
(35, 2, 'Ướp nguyên liệu với gia vị vừa miệng đun sôi trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815400/mamngon/recipes/jihqr5tr9iaz9oxukrql.jpg', 600),
(35, 3, 'Hầm nhỏ lửa cho gia vị ngấm đều đậm đà thơm ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815406/mamngon/recipes/hlefgir6xqcvqdedpbwv.jpg', 600),
(35, 4, 'Thêm nước cốt dừa tươi hoặc các loại topping đi kèm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815415/mamngon/recipes/loyausdaa0vcrdv82lc6.jpg', 600),
(35, 5, 'Múc món ăn ra tô dĩa trang trí bày lên bàn ăn dùng nóng cực ngon.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815422/mamngon/recipes/pv74knhmvxlcamtzr40m.jpg', 600),
(36, 1, 'Chuẩn bị và sơ chế sạch sẽ các nguyên liệu cho món Cà phê phin sữa đá Việt Nam.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815430/mamngon/recipes/t6ltnlvpzjxv3zjig7gy.jpg', 600),
(36, 2, 'Ướp nguyên liệu với gia vị vừa miệng đun sôi trong 20 phút.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815437/mamngon/recipes/h2quhk7zajx97krwyzsj.jpg', 600),
(36, 3, 'Hầm nhỏ lửa cho gia vị ngấm đều đậm đà thơm ngậy.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815445/mamngon/recipes/zowfwhb7nmb1pkoctrdz.jpg', 600),
(36, 4, 'Thêm nước cốt dừa tươi hoặc các loại topping đi kèm.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815477/mamngon/recipes/ql7itqdft1xpvs9b620o.jpg', 600),
(36, 5, 'Múc món ăn ra tô dĩa trang trí bày lên bàn ăn dùng nóng cực ngon.', 'https://res.cloudinary.com/dofssbkbd/image/upload/v1782815487/mamngon/recipes/e6he21rjalhjkb0v40eo.jpg', 600);

-- 6. Seed recipe_categories
INSERT INTO recipe_categories (recipe_id, category_id)
VALUES
(1, 1),
(1, 4),
(1, 5),
(2, 1),
(2, 4),
(3, 1),
(3, 4),
(3, 5),
(4, 1),
(4, 5),
(5, 1),
(5, 5),
(6, 1),
(6, 5),
(6, 6),
(7, 1),
(7, 4),
(8, 1),
(8, 4),
(9, 1),
(9, 6),
(10, 1),
(10, 6),
(11, 1),
(11, 5),
(12, 1),
(12, 5),
(13, 1),
(13, 5),
(13, 6),
(14, 5),
(14, 6),
(15, 2),
(15, 7),
(16, 1),
(16, 7),
(17, 1),
(18, 2),
(18, 7),
(19, 1),
(20, 1),
(21, 1),
(21, 6),
(22, 1),
(22, 4),
(22, 5),
(23, 1),
(24, 1),
(24, 6),
(25, 7),
(26, 2),
(26, 7),
(27, 3),
(28, 3),
(29, 1),
(30, 1),
(31, 6),
(32, 7),
(33, 3),
(34, 3),
(35, 3),
(36, 1);

